const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '../work-items');

let FEATURE_COLORS = {};

function loadAllItems() {
    const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.json'));
    let allItems = [];
    files.forEach(file => {
        const content = fs.readFileSync(path.join(DATA_DIR, file), 'utf8');
        const data = JSON.parse(content);

        // Populate dynamic feature colors from group definition
        if (data.groupDefinition) {
            FEATURE_COLORS[data.groupDefinition.name] = data.groupDefinition.color;
        }

        const items = data.items || [];
        // Sanitize items: Provide property-level defaults to ensure critical fields exist
        const sanitizedItems = items.map(item => ({
            ...item,
            metadata: {
                status: 'unknown',
                size: 'M',
                dependencies: [],
                ...item.metadata
            },
            timeline: {
                created: new Date().toISOString().split('T')[0],
                ...item.timeline
            }
        }));

        allItems = allItems.concat(sanitizedItems);
    });
    return allItems;
}

function sanitizeId(id) {
    return id.replace(/[-\.]/g, '_');
}

// ── Configuration ──────────────────────────────────────────────────

const PKG = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8'));
const CURRENT_MILESTONE = 'v' + PKG.version.split('.').slice(0, 2).join('.');

// ── Helpers ─────────────────────────────────────────────────────────

/**
 * Standardizes the Markdown rendering of a Work Item across different views.
 */
function formatWorkItemMarkdown(item, { showStatus = false, showSize = false, showDeps = false } = {}) {
    const status = item.metadata.status;
    let titleLine = `### ${item.id}: ${item.title}`;

    if (showStatus) {
        if (status === 'done') titleLine += ' ✅';
        else if (status === 'aborted') titleLine += ' 🚫';
        else titleLine += ` (Status: ${status})`;

        if (item.timeline?.completed) titleLine += ` (${item.timeline.completed})`;
    }

    let md = `${titleLine}\n\n`;

    if (status === 'pending' && !showStatus) {
        md += `- **Status**: ⏳ Pending\n`;
    }
    if (showSize) {
        md += `- **Size**: ${item.metadata.size || 'M'}\n`;
    }

    md += `- **Description**: ${item.description}\n`;

    if (item.details?.length > 0) {
        md += `- **Details**:\n`;
        item.details.forEach(d => md += `  - ${d}\n`);
    }

    if (showDeps) {
        const deps = item.metadata.dependencies?.length > 0 ? item.metadata.dependencies.join(', ') : 'none';
        md += `- **Dependencies**: ${deps}\n`;
    }

    return md;
}

// ── Views ────────────────────────────────────────────────────────────

function getBacklogView(items) {
    const activeItems = items.filter(item =>
        item.metadata.status === 'pending' &&
        (item.metadata.milestone === CURRENT_MILESTONE || !item.metadata.milestone)
    );
    let markdown = `---\ntitle: Active Work Items\nscope: tasks, progress, dependencies\naudience: [Lead_Engineer, Product_Architect]\n---\n\n# Active Backlog (${CURRENT_MILESTONE})\n\n`;
    markdown += `> This file is automatically generated. To update status, use \`node scripts/update-wi.js\`.\n\n`;

    const groups = {};
    activeItems.forEach(item => {
        const group = item.featureGroup || 'General';
        if (!groups[group]) groups[group] = [];
        groups[group].push(item);
    });

    Object.keys(groups).sort().forEach(groupName => {
        markdown += `## ${groupName}\n\n`;
        const groupItems = groups[groupName];
        groupItems.forEach(item => {
            markdown += formatWorkItemMarkdown(item, { showSize: true, showDeps: true }) + '\n';
        });
    });
    return markdown.trim() + "\n";
}

/**
 * Generates an inline SVG color swatch as an HTML img data URI.
 * Renders in VS Code preview and GitHub without external network requests.
 * @param {string} hex - CSS hex color (e.g. '#4ade80')
 * @returns {string} HTML img tag with embedded SVG
 */
function colorBox(hex) {
    const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='14' height='14'><rect width='14' height='14' fill='${hex}' rx='3'/></svg>`;
    const encoded = encodeURIComponent(svg);
    return `<img src="data:image/svg+xml,${encoded}" width="14" height="14" alt="${hex}"/>`;
}

/**
 * Builds the Feature Groups legend table from live JSON data.
 * Computes WI ID ranges and stabilization status per group dynamically.
 */
function buildFeatureGroupsLegend(items) {
    const groupData = {};

    items.forEach(item => {
        const group = item.featureGroup || 'General';
        if (!groupData[group]) {
            groupData[group] = {
                itemIds: [],
                isStabilized: true,
                color: FEATURE_COLORS[group] || FEATURE_COLORS['General'],
            };
        }
        groupData[group].itemIds.push(item.id);
        if (item.metadata.status !== 'done' && item.metadata.status !== 'aborted') {
            groupData[group].isStabilized = false;
        }
    });

    let table = `\n## Feature Groups\n\n`;
    table += `| Group | Color | Status |\n`;
    table += `| :--- | :--- | :--- |\n`;

    // Sort groups by their minimum WI ID numerically
    Object.keys(groupData)
        .sort((a, b) => {
            const minA = Math.min(...groupData[a].itemIds.map(id => parseFloat(id.replace('WI-', ''))));
            const minB = Math.min(...groupData[b].itemIds.map(id => parseFloat(id.replace('WI-', ''))));
            return minA - minB;
        })
        .forEach(groupName => {
            const data = groupData[groupName];
            const status = data.isStabilized ? '💎 Stabilized' : '🔵 Active';
            const colorCell = `${colorBox(data.color.fill)} \`${data.color.fill}\``;
            table += `| ${groupName} | ${colorCell} | ${status} |\n`;
        });

    return table;
}

function getRoadmapView(items) {
    let mermaidGraph = `graph LR\n`;
    let styles = `\n`;

    // Pre-calculate group stabilization status
    const groupStates = {};
    items.forEach(item => {
        const group = item.featureGroup || 'General';
        if (!groupStates[group]) groupStates[group] = { isStabilized: true };
        if (item.metadata.status !== 'done' && item.metadata.status !== 'aborted') {
            groupStates[group].isStabilized = false;
        }
    });

    items.forEach(item => {
        const mId = sanitizeId(item.id);
        const color = FEATURE_COLORS[item.featureGroup] || FEATURE_COLORS['General'];
        const status = item.metadata.status;
        const group = item.featureGroup || 'General';
        const isStabilized = groupStates[group].isStabilized;

        mermaidGraph += `    ${mId}["${item.id} ${item.title}"]\n`;

        if (status === 'aborted') {
            styles += `    style ${mId} fill:none,stroke-dasharray:5\n`;
        } else if (isStabilized) {
            // Stabilized Group Style: Unsaturated grey background with thin dashed border
            styles += `    style ${mId} fill:#f1f5f9,stroke:#94a3b8,stroke-width:1px,stroke-dasharray:2\n`;
        } else {
            const isDone = status === 'done';
            const stroke = isDone ? '#000' : color.stroke;
            const strokeWidth = isDone ? ',stroke-width:2.5px' : '';
            styles += `    style ${mId} fill:${color.fill},stroke:${stroke}${strokeWidth}\n`;
        }
    });

    items.forEach(item => {
        const mId = sanitizeId(item.id);
        if (item.metadata.dependencies?.length > 0) {
            item.metadata.dependencies.forEach(depId => {
                const mDepId = sanitizeId(depId);
                mermaidGraph += `    ${mDepId} --> ${mId}\n`;
            });
        }
    });

    return `---
title: Project Roadmap & Dependency Map
scope: milestones, dependencies, architecture-tracking
audience: [Product_Architect, Lead_Engineer, Quality_Control_Reviewer]
last_updated: ${new Date().toISOString().split('T')[0]}
---

# Project Roadmap & Dependency Map

\`\`\`mermaid
${mermaidGraph}${styles}\`\`\`
${buildFeatureGroupsLegend(items)}`.trim() + '\n';
}

function getChangelogView(items) {
    const completedItems = items.filter(item => item.metadata.status === 'done' || item.metadata.status === 'aborted');
    completedItems.sort((a, b) => a.id.localeCompare(b.id));

    let markdown = `---\ntitle: Project Changelog\nscope: history, completed-phases, archived-tasks\naudience: [Product_Architect, Lead_Engineer]\n---\n\n# Project Changelog\n\n`;

    const groups = {};
    completedItems.forEach(item => {
        const group = item.featureGroup || 'General';
        if (!groups[group]) groups[group] = [];
        groups[group].push(item);
    });

    Object.keys(groups).sort().forEach(groupName => {
        markdown += `## ${groupName}\n\n`;
        const groupItems = groups[groupName];
        groupItems.forEach(item => {
            markdown += formatWorkItemMarkdown(item, { showStatus: true }) + '\n';
        });
        markdown += '---\n\n';
    });
    return markdown.trim() + '\n';
}

function getFutureView(items) {
    const roadmapItems = items.filter(item =>
        (item.metadata.status === 'proposed' || item.metadata.status === 'pending') &&
        item.metadata.milestone !== CURRENT_MILESTONE &&
        item.metadata.milestone !== undefined
    );

    let markdown = `---\ntitle: Future Roadmap\nscope: future features, backlog\naudience: [Product_Architect, Lead_Engineer]\n---\n\n# Future Roadmap\n\n`;
    markdown += `> This roadmap outlines features scheduled for future exploration. Current targeted version: **${CURRENT_MILESTONE}**.\n\n`;

    const milestones = {};
    roadmapItems.forEach(item => {
        const ms = item.metadata.milestone || 'Backlog';
        if (!milestones[ms]) milestones[ms] = [];
        milestones[ms].push(item);
    });

    // Sort: v1.1, v1.2, ..., Backlog
    Object.keys(milestones).sort((a, b) => {
        if (a === 'Backlog') return 1;
        if (b === 'Backlog') return -1;
        return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });
    }).forEach(ms => {
        markdown += `## Milestone ${ms}\n\n`;
        const msItems = milestones[ms];
        msItems.forEach(item => {
            markdown += formatWorkItemMarkdown(item, { showStatus: true }) + '\n';
        });
    });
    return markdown.trim() + "\n";
}

// ── CLI Execution ──────────────────────────────────────────────────

const [viewType, outputPath] = process.argv.slice(2);

if (!viewType || !outputPath) {
    console.log('Usage: node scripts/generate-docs.js <backlog|roadmap|changelog|future> <output_path|"-">');
    process.exit(1);
}

const items = loadAllItems();
let result = '';

switch (viewType) {
    case 'backlog': result = getBacklogView(items); break;
    case 'roadmap': result = getRoadmapView(items); break;
    case 'changelog': result = getChangelogView(items); break;
    case 'future': result = getFutureView(items); break;
    default:
        console.error(`Error: Unknown view type "${viewType}"`);
        process.exit(1);
}

if (outputPath === '-') {
    process.stdout.write(result);
} else {
    fs.writeFileSync(outputPath, result);
    console.log(`✅ Successfully generated ${viewType} view at ${outputPath}`);
}
